sudo: false

jobs:
  include:
    - stage: build
      script:
        - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
        - export DOCKER_REPO=analogical/qotd-svc
        - export TAG=latest
        - docker build -t $DOCKER_REPO .
    - stage: deploy
        script:
          - docker tag $TAG
          - docker push $DOCKER_REPO
        if: branch = master
