sudo: false

jobs:
  include:
    - stage: build
      script: export DOCKER_REPO=analogical/qotd-svc
    - script: export TAG=latest
    - script: docker build -t $DOCKER_REPO .
    - stage: deploy
      if: branch = master
      script: echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
    - script: docker tag $TAG
    - script: docker push $DOCKER_REPO
