services:
  - docker

jobs:
  include:
    - stage: build
      script:
        - npm run docker:login
        - npm run docker:build
        - npm run docker:push
    - stage: deploy
      script: skip
      deploy:
        provider: script
        script: npm run docker:deploy
