services:
  - docker
stages:
  - build
  - stage: deploy
    if: branch = master
jobs:
  include:
    - stage: build
      script:
        - npm run docker:login
        - npm run docker:build
        - npm run docker:push
    - stage: tag docker image
      script: skip
      deploy:
        provider: script
        script: npm run docker:deploy
