sudo: required

services:
  - docker

language: node_js

install:
  - npm ci

script:
  - npm run test
  - npm run build

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export DOCKER_REPO=analogical/qotd-svc
  - export TAG=latest
  - docker build -t $DOCKER_REPO .
  - docker tag $TAG
  - docker push $DOCKER_REPO
