sudo: false

jobs:
  include:
    - stage: build
      script:
        - docker build -t analogical/qotd-svc .
    - stage: deploy
      if: branch = master
      script:
        - export TAG=latest
        - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
        - docker tag $TAG
        - docker push analogical/qotd-svc
