sudo: required

services:
  - docker
before_install:
  - docker build -t analogical/qotd-svc .
install:
  - echo "Nothing to install"
script:
  - echo "Nothing to run here"
deploy:
  provider: script
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push analogical/qotd-svc
